import type { AppLanguage } from '../../components/planner/types';

/**
 * Task categories — a SECONDARY filter axis for the checklist.
 *
 * The primary structure stays time-based (phases / month buckets generated by
 * checklistGenerator). Category is orthogonal: it groups tasks by *what kind of
 * work* they are (venue, catering, attire…) so couples can filter and see
 * per-category progress, the way Akad's category rail works.
 *
 * NOTE: this is a different concept from `GenerationSource['category']` in
 * checklistGenerator.ts, which means *provenance* ('base' | 'state' | 'scale'…).
 * Do not conflate the two.
 */

export type ChecklistCategoryId =
  | 'keperluan-asas'
  | 'nikah-protokol'
  | 'tempat-venue'
  | 'makanan-katering'
  | 'solekan-pakaian'
  | 'pelamin-dekorasi'
  | 'media-dokumentasi'
  | 'hiburan-aturcara'
  | 'jemputan-logistik';

export type ChecklistCategory = {
  id: ChecklistCategoryId;
  labelMs: string;
  labelEn: string;
  /** Matches a `Vendor.category` value when the category maps to a vendor type. */
  vendorCategory?: string;
  /** Lowercase keywords (matched as whole words) used to auto-classify a task. */
  keywords: string[];
};

/**
 * Ordered list. Order also acts as the tie-breaker when a task scores equally
 * across categories (earlier wins). More specific categories sit before the
 * generic `keperluan-asas` fallback.
 */
export const CHECKLIST_CATEGORIES: ChecklistCategory[] = [
  {
    id: 'nikah-protokol',
    labelMs: 'Nikah & Protokol',
    labelEn: 'Nikah & Protocol',
    keywords: [
      'kursus pra-perkahwinan', 'kursus', 'akad', 'nikah', 'tok kadi', 'kadi',
      'pencatat nikah', 'jurunikah', 'wali', 'saksi', 'mas kahwin', 'maskahwin',
      'hantaran', 'kebenaran nikah', 'pejabat agama', 'sijil nikah', 'sijil lahir',
      'dokumen', 'surat persetujuan', 'berian', 'jpj', 'epf', 'status', 'bercerai',
      'adat', 'istikharah', 'solat'
    ]
  },
  {
    id: 'media-dokumentasi',
    labelMs: 'Media & Dokumentasi',
    labelEn: 'Media & Documentation',
    vendorCategory: 'Jurufoto & Juruvideo',
    keywords: [
      'jurugambar', 'jurufoto', 'juruvideo', 'videographer', 'photographer',
      'fotografi', 'gambar', 'foto', 'video', 'drone', 'photo booth', 'photobooth',
      'highlight', 'backup', 'liputan', 'live feed'
    ]
  },
  {
    id: 'solekan-pakaian',
    labelMs: 'Solekan & Pakaian',
    labelEn: 'Makeup & Attire',
    vendorCategory: 'Andaman/MUA',
    keywords: [
      'mua', 'makeup', 'make up', 'andaman', 'solek', 'hair', 'hairstylist',
      'baju pengantin', 'baju sanding', 'baju', 'fitting', 'butik', 'telekung',
      'aksesori', 'attire', 'beauty', 'facial', 'grooming', 'wardrobe'
    ]
  },
  {
    id: 'pelamin-dekorasi',
    labelMs: 'Pelamin & Dekorasi',
    labelEn: 'Dais & Decor',
    vendorCategory: 'Pelamin & Dekorasi',
    keywords: [
      'pelamin', 'dekorasi', 'decor', 'tema', 'konsep', 'moodboard', 'backdrop',
      'bunga', 'lighting', 'fairy lights', 'signage', 'walkway', 'table decor',
      'photo booth backdrop'
    ]
  },
  {
    id: 'makanan-katering',
    labelMs: 'Makanan & Katering',
    labelEn: 'Food & Catering',
    vendorCategory: 'Katerer',
    keywords: [
      'katering', 'katerer', 'caterer', 'food tasting', 'menu', 'buffet', 'lauk',
      'hidangan', 'sharing plate', 'live cooking', 'food', 'lemang', 'dodol',
      'ketupat', 'pucuk rebung', 'welcome drink'
    ]
  },
  {
    id: 'hiburan-aturcara',
    labelMs: 'Hiburan & Aturcara',
    labelEn: 'Entertainment & Run-sheet',
    keywords: [
      'mc', 'juruacara', 'pengacara', 'kompang', 'dj', 'live band', 'band',
      'hiburan', 'pa system', 'sound', 'mikrofon', 'speaker', 'run sheet',
      'flow majlis', 'flow', 'script', 'lagu', 'jadual hari majlis', 'kompang'
    ]
  },
  {
    id: 'tempat-venue',
    labelMs: 'Tempat & Venue',
    labelEn: 'Venue & Place',
    vendorCategory: 'Dewan & Venue',
    keywords: [
      'dewan', 'masjid', 'restoran', 'venue', 'hotel', 'ballroom', 'surau',
      'khemah', 'kanopi', 'canopy', 'parking', 'cleaning', 'crowd', 'security',
      'zones', 'lokasi majlis'
    ]
  },
  {
    id: 'jemputan-logistik',
    labelMs: 'Jemputan & Logistik',
    labelEn: 'Invites & Logistics',
    keywords: [
      'kad jemputan', 'jemputan', 'rsvp', 'headcount', 'seating', 'susun atur meja',
      'door gift', 'cenderamata', 'cenderahati', 'penginapan', 'accommodation',
      'transport', 'bas', 'e-hailing', 'shuttle', 'emergency kit', 'pack beg',
      'charge', 'gadget', 'powerbank', 'thank you', 'tip vendor', 'crew', 'krew'
    ]
  },
  {
    id: 'keperluan-asas',
    labelMs: 'Keperluan Asas',
    labelEn: 'Foundations',
    // Fallback bucket — also the default when nothing matches.
    keywords: [
      'tarikh', 'bajet', 'budget', 'tabungan', 'akaun', 'kewangan', 'anggaran',
      'rancang', 'planning', 'cuti', 'pax'
    ]
  }
];

const DEFAULT_CATEGORY: ChecklistCategoryId = 'keperluan-asas';

const CATEGORY_BY_ID = new Map<ChecklistCategoryId, ChecklistCategory>(
  CHECKLIST_CATEGORIES.map((c) => [c.id, c])
);

// Precompile keyword matchers once. Whole-word match so short tokens like "mc"
// or "dj" don't fire inside unrelated words.
const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const COMPILED: Array<{ id: ChecklistCategoryId; res: RegExp[] }> = CHECKLIST_CATEGORIES.map((c) => ({
  id: c.id,
  res: c.keywords.map((kw) => new RegExp(`(?:^|[^a-z0-9])${escapeRe(kw)}(?:$|[^a-z0-9])`, 'i'))
}));

/**
 * Classify a task into a category by keyword score. Highest score wins; ties
 * break toward whichever category appears first in CHECKLIST_CATEGORIES. Tasks
 * that match nothing fall back to 'keperluan-asas'.
 */
export function categorizeTask(text: string): ChecklistCategoryId {
  const haystack = ` ${(text || '').toLowerCase()} `;
  let bestId: ChecklistCategoryId = DEFAULT_CATEGORY;
  let bestScore = 0;
  for (const entry of COMPILED) {
    let score = 0;
    for (const re of entry.res) if (re.test(haystack)) score += 1;
    if (score > bestScore) {
      bestScore = score;
      bestId = entry.id;
    }
  }
  return bestId;
}

/**
 * Like categorizeTask but returns null when no keyword matches (score = 0),
 * so callers can distinguish "no match" from "default bucket".
 */
export function tryDetectCategory(text: string): ChecklistCategoryId | null {
  if (!text || text.trim().length < 3) return null;
  const haystack = ` ${text.toLowerCase()} `;
  let bestId: ChecklistCategoryId | null = null;
  let bestScore = 0;
  for (const entry of COMPILED) {
    let score = 0;
    for (const re of entry.res) if (re.test(haystack)) score += 1;
    if (score > bestScore) {
      bestScore = score;
      bestId = entry.id;
    }
  }
  return bestId;
}

export function getCategory(id: string | undefined): ChecklistCategory | undefined {
  return id ? CATEGORY_BY_ID.get(id as ChecklistCategoryId) : undefined;
}

export function getCategoryLabel(id: string | undefined, lang: AppLanguage): string {
  const cat = getCategory(id);
  if (!cat) return '';
  return lang === 'ms' ? cat.labelMs : cat.labelEn;
}
